title: Stories by Double-A (18+)
description: I write interactive furry vore literature. If that's not a thing you're interested in reading, I'm not sure what you're doing here.

theme: jekyll-theme-midnight
logo: /images/aa-icon.png

github.is_user_page: false
